import { Controller, Get, Post, Body, Patch, Param, Delete, UseGuards, Query, ForbiddenException } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { PassesService } from './passes.service';
import { CreatePassDto } from './dto/create-pass.dto';
import { UpdatePassDto } from './dto/update-pass.dto';
import { PassResponseDto } from './dto/pass-response.dto';
import { PassListQueryDto } from './dto/pass-list-query.dto';
import { PassStatsResponseDto } from './dto/pass-stats-response.dto';
import { PassDateGroupDto } from './dto/pass-date-group.dto';
import { RedeemPassDto } from './dto/redeem-pass.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../auth/guards/roles.guard';
import { Roles } from '../auth/decorators/roles.decorator';
import { GetUser } from '../auth/decorators/get-user.decorator';
import { UserRole } from '../users/user.entity';

@ApiTags('Passes')
@ApiBearerAuth('access-token')
@Controller('passes')
@UseGuards(JwtAuthGuard, RolesGuard)
export class PassesController {
  constructor(private readonly passesService: PassesService) {}

  @Post()
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Automatically generate a multi-item pass (Login required)' })
  @ApiResponse({ status: 201, description: 'Pass created successfully', type: PassResponseDto })
  @ApiResponse({ status: 400, description: 'Asset inactive, belongs to different outlet, or invalid discount/quantities' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async create(@Body() createPassDto: CreatePassDto, @GetUser() user: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : undefined;
    const data = await this.passesService.create(createPassDto, user.userId, user.role, filterOutletId);
    return {
      message: 'Pass created successfully',
      data,
    };
  }

  @Get('search')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Search passes by pass number, customer name, or customer mobile (for redemption workflow)' })
  @ApiQuery({ name: 'q', required: true, description: 'Pass number, customer name, or mobile' })
  @ApiResponse({ status: 200, description: 'Matching passes' })
  async search(@Query('q') q: string, @GetUser() user: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : undefined;
    const data = await this.passesService.search(q, filterOutletId);
    return {
      message: 'Pass search results',
      data,
    };
  }

  @Get()
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get all passes with pagination, search, filters, and sorting' })
  @ApiResponse({ status: 200, description: 'Paginated list of passes' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findAll(@Query() query: PassListQueryDto, @GetUser() user: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : query.outletId;
    const filterEmployeeId = user.role === UserRole.EMPLOYEE ? undefined : query.employeeId;

    const data = await this.passesService.findAll({
      ...query,
      outletId: filterOutletId,
      employeeId: filterEmployeeId,
      paginated: true,
    });
    return {
      message: 'Passes retrieved successfully',
      data,
    };
  }

  @Get('my-passes')
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get passes generated by the logged-in employee with pagination, filters, and sorting' })
  @ApiResponse({ status: 200, description: 'Paginated list of employee passes' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findMyPasses(@Query() query: PassListQueryDto, @GetUser() user: any) {
    const data = await this.passesService.findAll({
      ...query,
      employeeId: user.userId,
      outletId: user.outletId,
      paginated: true,
    });
    return {
      message: 'My passes retrieved successfully',
      data,
    };
  }

  @Get('stats/today')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: "Get today's pass statistics" })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: "Today's statistics", type: PassStatsResponseDto })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async getTodayStats(@Query('outletId') outletId?: string, @GetUser() user?: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (outletId ? +outletId : undefined);
    const data = await this.passesService.getTodayStats(filterOutletId);
    return {
      message: "Today's statistics retrieved successfully",
      data,
    };
  }

  @Get('customer/:customerId')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get passes by customer ID' })
  @ApiResponse({ status: 200, description: 'List of customer passes', type: [PassResponseDto] })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findByCustomer(@Param('customerId') customerId: string, @GetUser() user: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : undefined;
    const data = await this.passesService.findByCustomer(+customerId, filterOutletId);
    return {
      message: 'Passes for customer retrieved successfully',
      data,
    };
  }

  @Get('outlet/:outletId')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get passes by outlet ID' })
  @ApiResponse({ status: 200, description: 'List of outlet passes', type: [PassResponseDto] })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  async findByOutlet(@Param('outletId') outletId: string, @GetUser() user: any) {
    if (user.role === UserRole.EMPLOYEE && user.outletId !== +outletId) {
      throw new ForbiddenException('Forbidden. Employees can only view their own outlet.');
    }
    const data = await this.passesService.findByOutlet(+outletId);
    return {
      message: 'Passes for outlet retrieved successfully',
      data,
    };
  }

  @Get('date-range')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN)
  @ApiOperation({ summary: 'Get passes by date range (Admin only)' })
  @ApiQuery({ name: 'startDate', required: true, type: String })
  @ApiQuery({ name: 'endDate', required: true, type: String })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'List of passes', type: [PassResponseDto] })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findByDateRange(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @Query('outletId') outletId?: string,
  ) {
    const data = await this.passesService.findByDateRange(
      new Date(startDate),
      new Date(endDate),
      outletId ? +outletId : undefined,
    );
    return {
      message: 'Passes for date range retrieved successfully',
      data,
    };
  }

  @Get('date-wise')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN)
  @ApiOperation({ summary: 'Get admin passes grouped by date (Admin only)' })
  @ApiResponse({ status: 200, description: 'Grouped passes', type: [PassDateGroupDto] })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findDateWise(@Query() query: PassListQueryDto) {
    const data = await this.passesService.findDateWise({
      status: query.status,
      fromDate: query.fromDate ? new Date(`${query.fromDate}T00:00:00.000Z`) : undefined,
      toDate: query.toDate ? new Date(`${query.toDate}T23:59:59.999Z`) : undefined,
    });
    return {
      message: 'Date-wise passes retrieved successfully',
      data,
    };
  }

  @Post(':id/redeem')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Redeem pass items (Login required)' })
  @ApiResponse({ status: 200, description: 'Pass redeemed successfully', type: PassResponseDto })
  @ApiResponse({ status: 400, description: 'Invalid redeem quantity, pass fully redeemed, or pass cancelled' })
  @ApiResponse({ status: 404, description: 'Pass or pass item not found' })
  async redeem(
    @Param('id') id: string,
    @Body() redeemPassDto: RedeemPassDto,
    @GetUser() user: any,
  ) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : undefined;
    const data = await this.passesService.redeem(+id, redeemPassDto, user.userId, filterOutletId);
    return {
      message: 'Pass redeemed successfully',
      data,
    };
  }

  @Get(':id/redemptions')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get pass redemption history' })
  @ApiResponse({ status: 200, description: 'Pass redemption history' })
  @ApiResponse({ status: 404, description: 'Pass not found' })
  async getRedemptions(@Param('id') id: string) {
    const data = await this.passesService.getRedemptions(+id);
    return {
      message: 'Redemption history retrieved successfully',
      data,
    };
  }

  @Get(':id')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get pass details by ID' })
  @ApiResponse({ status: 200, description: 'Pass details', type: PassResponseDto })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 404, description: 'Pass not found' })
  async findOne(@Param('id') id: string, @GetUser() user: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : undefined;
    const data = await this.passesService.findOneMapped(+id, filterOutletId);
    return {
      message: 'Pass retrieved successfully',
      data,
    };
  }

  @Patch(':id')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN)
  @ApiOperation({ summary: 'Update a pass (Admin only)' })
  @ApiResponse({ status: 200, description: 'Pass updated successfully', type: PassResponseDto })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 404, description: 'Pass not found' })
  async update(@Param('id') id: string, @Body() updatePassDto: UpdatePassDto) {
    const data = await this.passesService.update(+id, updatePassDto);
    return {
      message: 'Pass updated successfully',
      data,
    };
  }

  @Delete(':id')
  @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN)
  @ApiOperation({ summary: 'Delete a pass (Admin only)' })
  @ApiResponse({ status: 200, description: 'Pass deleted successfully' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiResponse({ status: 404, description: 'Pass not found' })
  async remove(@Param('id') id: string) {
    await this.passesService.remove(+id);
    return {
      message: 'Pass deleted successfully',
      data: null,
    };
  }
}
