import { ApiProperty } from "@nestjs/swagger";

export class MostUsedAssetsReportDto {
  @ApiProperty({ example: 5 })
  assetId: number;

  @ApiProperty({ example: "MC-001" })
  assetCode: string;

  @ApiProperty({ example: "Massage Chair 1" })
  assetName: string;

  @ApiProperty({
    example: 25,
    description: "Sum of quantities rented across all orders",
  })
  totalUsage: number;

  @ApiProperty({
    example: 2500.0,
    description: "Total revenue generated by the asset",
  })
  totalRevenue: number;
}
