import { Controller, Get, Post, Body, Patch, Param, Delete, UseGuards, Query } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { TokensService } from './tokens.service';
import { CreateTokenDto } from './dto/create-token.dto';
import { UpdateTokenDto } from './dto/update-token.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../auth/guards/roles.guard';
import { Roles } from '../auth/decorators/roles.decorator';
import { GetUser } from '../auth/decorators/get-user.decorator';
import { UserRole } from '../users/user.entity';

@ApiTags('Tokens')
@ApiBearerAuth()
@Controller('tokens')
@UseGuards(JwtAuthGuard, RolesGuard)
export class TokensController {
  constructor(private readonly tokensService: TokensService) {}

  @Post()
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Generate a new token (Employee only)' })
  @ApiResponse({ status: 201, description: 'Token created successfully' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  create(@Body() createTokenDto: CreateTokenDto, @GetUser() user: any) {
    return this.tokensService.create(createTokenDto, user.userId, user.outletId);
  }

  @Get()
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get all tokens' })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'List of all tokens' })
  findAll(@Query('outletId') outletId?: string, @GetUser() user?: any) {
    // If employee, only show tokens from their outlet
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (outletId ? +outletId : undefined);
    return this.tokensService.findAll(filterOutletId);
  }

  @Get('my-tokens')
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get tokens generated by logged-in employee' })
  @ApiResponse({ status: 200, description: 'List of employee tokens' })
  findMyTokens(@GetUser() user: any) {
    return this.tokensService.findByUser(user.userId, user.outletId);
  }

  @Get('stats/today')
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get today\'s statistics' })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'Today\'s token statistics' })
  getTodayStats(@Query('outletId') outletId?: string, @GetUser() user?: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (outletId ? +outletId : undefined);
    return this.tokensService.getTodayStats(filterOutletId);
  }

  @Get('outlet/:outletId')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Get all tokens by outlet (Admin only)' })
  @ApiResponse({ status: 200, description: 'List of tokens for outlet' })
  findByOutlet(@Param('outletId') outletId: string) {
    return this.tokensService.findByOutlet(+outletId);
  }

  @Get('date-range')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Get tokens by date range (Admin only)' })
  @ApiQuery({ name: 'startDate', required: true, type: String })
  @ApiQuery({ name: 'endDate', required: true, type: String })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'List of tokens in date range' })
  findByDateRange(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @Query('outletId') outletId?: string,
  ) {
    return this.tokensService.findByDateRange(
      new Date(startDate),
      new Date(endDate),
      outletId ? +outletId : undefined,
    );
  }

  @Get(':id')
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get a token by ID' })
  @ApiResponse({ status: 200, description: 'Token details' })
  @ApiResponse({ status: 404, description: 'Token not found' })
  findOne(@Param('id') id: string) {
    return this.tokensService.findOne(+id);
  }

  @Patch(':id')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Update a token (Admin only)' })
  @ApiResponse({ status: 200, description: 'Token updated successfully' })
  @ApiResponse({ status: 404, description: 'Token not found' })
  update(@Param('id') id: string, @Body() updateTokenDto: UpdateTokenDto) {
    return this.tokensService.update(+id, updateTokenDto);
  }

  @Delete(':id')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Delete a token (Admin only)' })
  @ApiResponse({ status: 200, description: 'Token deleted successfully' })
  @ApiResponse({ status: 404, description: 'Token not found' })
  remove(@Param('id') id: string) {
    return this.tokensService.remove(+id);
  }
}
