import { Controller, Get, Post, Body, Patch, Param, Delete, UseGuards, Query } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { TokensService } from './tokens.service';
import { CreateTokenDto } from './dto/create-token.dto';
import { UpdateTokenDto } from './dto/update-token.dto';
import { TokenResponseDto } from './dto/token-response.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../auth/guards/roles.guard';
import { Roles } from '../auth/decorators/roles.decorator';
import { GetUser } from '../auth/decorators/get-user.decorator';
import { UserRole } from '../users/user.entity';

@ApiTags('Tokens')
@ApiBearerAuth()
@Controller('tokens')
@UseGuards(JwtAuthGuard, RolesGuard)
export class TokensController {
  constructor(private readonly tokensService: TokensService) { }

  @Post()
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Generate a new token (Employee only)' })
  @ApiResponse({ status: 201, description: 'Token created successfully', type: TokenResponseDto })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  async create(@Body() createTokenDto: CreateTokenDto, @GetUser() user: any) {
    const data = await this.tokensService.create(createTokenDto, user.userId, user.outletId);
    return {
      message: 'Token created successfully',
      data,
    };
  }

  @Get()
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get all tokens' })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'List of all tokens', type: [TokenResponseDto] })
  async findAll(@Query('outletId') outletId?: string, @GetUser() user?: any) {
    // If employee, only show tokens from their outlet
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (outletId ? +outletId : undefined);
    const data = await this.tokensService.findAll(filterOutletId);
    return {
      message: 'Tokens retrieved successfully',
      data,
    };
  }

  @Get('my-tokens')
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get tokens generated by logged-in employee' })
  @ApiResponse({ status: 200, description: 'List of employee tokens', type: [TokenResponseDto] })
  async findMyTokens(@GetUser() user: any) {
    const data = await this.tokensService.findByUser(user.userId, user.outletId);
    return {
      message: 'My tokens retrieved successfully',
      data,
    };
  }

  @Get('stats/today')
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get today\'s statistics' })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'Today\'s token statistics' })
  async getTodayStats(@Query('outletId') outletId?: string, @GetUser() user?: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (outletId ? +outletId : undefined);
    const data = await this.tokensService.getTodayStats(filterOutletId);
    return {
      message: 'Today\'s statistics retrieved successfully',
      data,
    };
  }

  @Get('outlet/:outletId')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Get all tokens by outlet (Admin only)' })
  @ApiResponse({ status: 200, description: 'List of tokens for outlet', type: [TokenResponseDto] })
  async findByOutlet(@Param('outletId') outletId: string) {
    const data = await this.tokensService.findByOutlet(+outletId);
    return {
      message: 'Tokens for outlet retrieved successfully',
      data,
    };
  }

  @Get('date-range')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Get tokens by date range (Admin only)' })
  @ApiQuery({ name: 'startDate', required: true, type: String })
  @ApiQuery({ name: 'endDate', required: true, type: String })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'List of tokens in date range', type: [TokenResponseDto] })
  async findByDateRange(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @Query('outletId') outletId?: string,
  ) {
    const data = await this.tokensService.findByDateRange(
      new Date(startDate),
      new Date(endDate),
      outletId ? +outletId : undefined,
    );
    return {
      message: 'Tokens for date range retrieved successfully',
      data,
    };
  }

  @Get(':id')
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get a token by ID' })
  @ApiResponse({ status: 200, description: 'Token details', type: TokenResponseDto })
  @ApiResponse({ status: 404, description: 'Token not found' })
  async findOne(@Param('id') id: string) {
    const data = await this.tokensService.findOne(+id);
    return {
      message: 'Token retrieved successfully',
      data,
    };
  }

  @Patch(':id')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Update a token (Admin only)' })
  @ApiResponse({ status: 200, description: 'Token updated successfully', type: TokenResponseDto })
  @ApiResponse({ status: 404, description: 'Token not found' })
  async update(@Param('id') id: string, @Body() updateTokenDto: UpdateTokenDto) {
    const data = await this.tokensService.update(+id, updateTokenDto);
    return {
      message: 'Token updated successfully',
      data,
    };
  }

  @Delete(':id')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Delete a token (Admin only)' })
  @ApiResponse({ status: 200, description: 'Token deleted successfully' })
  @ApiResponse({ status: 404, description: 'Token not found' })
  async remove(@Param('id') id: string) {
    await this.tokensService.remove(+id);
    return {
      message: 'Token deleted successfully',
      data: null,
    };
  }
}
