import { Controller, Get, Post, Body, Patch, Param, Delete, UseGuards, Query } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth, ApiQuery, ApiBody, ApiCreatedResponse, ApiOkResponse, ApiBadRequestResponse, ApiForbiddenResponse, ApiNotFoundResponse, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { TokensService } from './tokens.service';
import { CreateTokenDto } from './dto/create-token.dto';
import { UpdateTokenDto } from './dto/update-token.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../auth/guards/roles.guard';
import { Roles } from '../auth/decorators/roles.decorator';
import { GetUser } from '../auth/decorators/get-user.decorator';
import { UserRole } from '../users/user.entity';
import { EmptyApiResponseDto, ErrorApiResponseDto, TokenItemApiResponseDto, TokenListApiResponseDto, TokenStatsApiResponseDto } from './dto/token-api-response.dto';
import { TokenListQueryDto } from './dto/token-list-query.dto';

@ApiTags('Tokens')
@ApiBearerAuth('access-token')
@Controller('tokens')
@UseGuards(JwtAuthGuard, RolesGuard)
export class TokensController {
  constructor(private readonly tokensService: TokensService) { }

  @Post()
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Generate a new token for the logged-in employee outlet' })
  @ApiBody({
    type: CreateTokenDto,
    examples: {
      default: {
        summary: 'Create outlet token',
        value: {
          chairId: 1,
          amount: 50,
          status: 'ACTIVE',
        },
      },
    },
  })
  @ApiCreatedResponse({ description: 'Token created successfully', type: TokenItemApiResponseDto })
  @ApiBadRequestResponse({ description: 'Chair is invalid for this outlet or payload is invalid', type: ErrorApiResponseDto })
  @ApiForbiddenResponse({ description: 'Forbidden', type: ErrorApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async create(@Body() createTokenDto: CreateTokenDto, @GetUser() user: any) {
    const data = await this.tokensService.create(createTokenDto, user.userId, user.outletId);
    return {
      message: 'Token created successfully',
      data,
    };
  }

  @Get()
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get frontend-ready token list' })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiQuery({ name: 'status', required: false, enum: ['ACTIVE', 'COMPLETED', 'CANCELLED'] })
  @ApiQuery({ name: 'chairId', required: false, type: Number })
  @ApiQuery({ name: 'userId', required: false, type: Number })
  @ApiQuery({ name: 'fromDate', required: false, type: String })
  @ApiQuery({ name: 'toDate', required: false, type: String })
  @ApiOkResponse({ description: 'List of tokens', type: TokenListApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async findAll(@Query() query: TokenListQueryDto, @GetUser() user?: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (query.outletId ? +query.outletId : undefined);
    const filterUserId = user.role === UserRole.EMPLOYEE ? undefined : (query.userId ? +query.userId : undefined);
    const data = await this.tokensService.findAll({
      outletId: filterOutletId,
      status: query.status,
      chairId: query.chairId ? +query.chairId : undefined,
      userId: filterUserId,
      fromDate: query.fromDate ? new Date(`${query.fromDate}T00:00:00.000Z`) : undefined,
      toDate: query.toDate ? new Date(`${query.toDate}T23:59:59.999Z`) : undefined,
    });
    return {
      message: 'Tokens retrieved successfully',
      data,
    };
  }

  @Get('my-tokens')
  @Roles(UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get tokens generated by logged-in employee' })
  @ApiQuery({ name: 'status', required: false, enum: ['ACTIVE', 'COMPLETED', 'CANCELLED'] })
  @ApiQuery({ name: 'chairId', required: false, type: Number })
  @ApiQuery({ name: 'fromDate', required: false, type: String })
  @ApiQuery({ name: 'toDate', required: false, type: String })
  @ApiOkResponse({ description: 'List of employee tokens', type: TokenListApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async findMyTokens(@Query() query: TokenListQueryDto, @GetUser() user: any) {
    const data = await this.tokensService.findByUser(user.userId, user.outletId, query);
    return {
      message: 'My tokens retrieved successfully',
      data,
    };
  }

  @Get('stats/today')
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get today\'s token statistics for the employee outlet or a selected admin outlet' })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiOkResponse({ description: 'Today\'s token statistics', type: TokenStatsApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async getTodayStats(@Query('outletId') outletId?: string, @GetUser() user?: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : (outletId ? +outletId : undefined);
    const data = await this.tokensService.getTodayStats(filterOutletId);
    return {
      message: 'Today\'s statistics retrieved successfully',
      data,
    };
  }

  @Get('outlet/:outletId')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Get all tokens by outlet (Admin only)' })
  @ApiOkResponse({ description: 'List of tokens for outlet', type: TokenListApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async findByOutlet(@Param('outletId') outletId: string) {
    const data = await this.tokensService.findByOutlet(+outletId);
    return {
      message: 'Tokens for outlet retrieved successfully',
      data,
    };
  }

  @Get('date-range')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Get tokens by date range (Admin only)' })
  @ApiQuery({ name: 'startDate', required: true, type: String })
  @ApiQuery({ name: 'endDate', required: true, type: String })
  @ApiQuery({ name: 'outletId', required: false, type: Number })
  @ApiOkResponse({ description: 'List of tokens in date range', type: TokenListApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async findByDateRange(
    @Query('startDate') startDate: string,
    @Query('endDate') endDate: string,
    @Query('outletId') outletId?: string,
  ) {
    const data = await this.tokensService.findByDateRange(
      new Date(startDate),
      new Date(endDate),
      outletId ? +outletId : undefined,
    );
    return {
      message: 'Tokens for date range retrieved successfully',
      data,
    };
  }

  @Get(':id')
  @Roles(UserRole.ADMIN, UserRole.EMPLOYEE)
  @ApiOperation({ summary: 'Get a token by ID' })
  @ApiOkResponse({ description: 'Token details', type: TokenItemApiResponseDto })
  @ApiNotFoundResponse({ description: 'Token not found', type: ErrorApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async findOne(@Param('id') id: string, @GetUser() user: any) {
    const filterOutletId = user.role === UserRole.EMPLOYEE ? user.outletId : undefined;
    const data = await this.tokensService.findOne(+id, filterOutletId);
    return {
      message: 'Token retrieved successfully',
      data,
    };
  }

  @Patch(':id')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Update a token (Admin only)' })
  @ApiBody({
    type: UpdateTokenDto,
    examples: {
      default: {
        summary: 'Update amount or status',
        value: {
          amount: 50,
          status: 'COMPLETED',
        },
      },
    },
  })
  @ApiOkResponse({ description: 'Token updated successfully', type: TokenItemApiResponseDto })
  @ApiNotFoundResponse({ description: 'Token not found', type: ErrorApiResponseDto })
  @ApiBadRequestResponse({ description: 'Invalid payload', type: ErrorApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async update(@Param('id') id: string, @Body() updateTokenDto: UpdateTokenDto) {
    const data = await this.tokensService.update(+id, updateTokenDto);
    return {
      message: 'Token updated successfully',
      data,
    };
  }

  @Delete(':id')
  @Roles(UserRole.ADMIN)
  @ApiOperation({ summary: 'Delete a token (Admin only)' })
  @ApiOkResponse({ description: 'Token deleted successfully', type: EmptyApiResponseDto })
  @ApiNotFoundResponse({ description: 'Token not found', type: ErrorApiResponseDto })
  @ApiUnauthorizedResponse({ description: 'Unauthorized', type: ErrorApiResponseDto })
  async remove(@Param('id') id: string) {
    await this.tokensService.remove(+id);
    return {
      message: 'Token deleted successfully',
      data: null,
    };
  }
}
